data_loader:
  file_path: "data/sample_data.csv"
  file_type: "csv"
transformation:
  normalize: false
  scaling_method: "minmax"
model:
  type: "linear" # Options: "linear" or "tree"
mlflow:
  tracking_uri: "http://mlflow:5000"
  experiment_name: "ml_data_pipeline_experiments"