mlflow:
  tracking_uri: "http://127.0.0.1:5001"
  experiment_name: "development_exp_1"
data_loader:
  file_path: "data/sample_data_dev.csv"
  file_type: "csv"
transformation:
  normalize: false
  scaling_method: "minmax"
model:
  type: "tree" # Options: "linear" or "tree"
